---
title: "API Exercises"
author: "Geoffrey Arnold"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr) # http rest requests
library(jsonlite) # fromJSON
library(utils) # URLencode functions
library(rgdal) # readOGR
```

## WPRDC API Call

```{r blotter}
# Generate URL
url <- URLencode('https://data.wprdc.org/api/action/datastore_search_sql?sql=SELECT * FROM "1797ead8-8262-41cc-9099-cbc8a161924b"', repeated = TRUE)
# Send request
get <- GET(url)
# Retrieve results
results <- fromJSON(content(get, "text"))$result$records
# View Records
View(results)
```

## Esri Call

```{r esri}
# Load as geojson
polls <- readOGR("https://services1.arcgis.com/vdNDkVykv9vEWFX4/ArcGIS/rest/services/Allegheny_County_Polling_Places_May2019/FeatureServer/0/query?where=MuniName+%3D+%27Pittsburgh%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=")
# Plot polling locations
plot(polls)
```